package Classe.OOheranca;

public enum Direcao {

    NORTE, LESTE, SUL, OESTE; //LISTA DOS ELEMENTOS SEPARADO POR VIRGULAS
    //N REPRESENTA STRING NEM VALOR NUMERICO
    //POSSO TER METODOS E ATRIBUTOS EM ENUMERAÇÃO
    //UM ENUM TBM DEFINE UM TIPO COMO UMA CLASSE

}
